- name: configurating the db servers
  hosts: db
  become: yes
  vars_prompt:
  - name: givepass
    prompt: please enter the password
  tasks:
  - name: install the mysql database
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  - name: start and enable the mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: installing the python dependencies
    ansible.builtin.pip:
      name:
      - PyMySql
      - cryptography
      executable: pip3.9

  - name: check db connection
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ givepass }}"
      login_host: 172.31.21.239
      filter: version
    ignore_errors: yes    
    register: mysqloutput

  - name: giving the output
    ansible.builtin.debug:
      msg: "output:  {{mysqloutput}}"

  - name: setup root password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{givepass}}"
    when: mysqloutput.failed is true   

      