- name: configurating the db servers
  hosts: db
  become: yes
  vars:
    givepass: PASSWORD
    prompt: please enter the password
  tasks:
  - name: install the mysql database
    ansible.builtin.dnf:
      name: mysql
      state: latest
  - name: start and enable the mysql
    ansible.builtin.service:
      name: mysql
      state: started
  - name: configuring the passwords
    ansible.builtin.command: mysql_secure_installation --set-root-pass {{givepass}}