- name: configurating the db servers
  hosts: db
  become: yes
  vars_prompt:
  - name: givepass
    prompt: please enter the password
  tasks:
  - name: install the mysql database
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  - name: start and enable the mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: check db connection
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: 54.174.221.108      