- name: configurating the db servers
  hosts: db
  become: yes
  vars_prompt:
    givepass: PASSWORD
    prompt: please enter the password
  tasks:
  - name: install the mysql database
    ansible.builtin.dnf:
      name: mysql-server
      state: latest
  - name: start and enable the mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: configuring the passwords
    ansible.builtin.command: mysql_secure_installation --set-root-pass {{givepass}}