- name: configurating the fronted server
  hosts: fronted
  become: yes
  vars:
  tasks:
  - name: installing the nginx server
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: enabling and starting the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  - name: Remove file (delete file)
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: absent

  - name: downloading the fronted content
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip 

  - name: unzipping the content
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip 
      dest: /usr/share/nginx/html/
      remote_src: yes 

  - name: copying the fronted service into systems
    ansible.builtin.copy:
      src: expense.conf 
      dest: vim /etc/nginx/default.d/expense.conf

  - name: restartingthe nginx
    ansible.builtin.service:
      name: nginx
      state: restarted

  

  